### PR TITLE
Upgrade of logbeat to 6.1.1 and new parameter DOCKLOGBEAT_SCAN_FRECUENCY

### PR DESCRIPTION
**Pull request by robertodocampo**
* New parameter DOCKLOGBEAT_SCAN_FRECUENCY that permits customize the scan frecuency of the container logs
* Upgrade to beats 6.1.1

### CODE REVIEW

**Comment by Vad1mo** [comment]
@robertodocampo could you resolve the conflicts?

**Comment by Vad1mo** [comment]
@irasnyd will you merge this PR?

**Comment by robertodocampo** [comment]
I upgrade the dockergen version to the master. The rest of the vars seems to be ok

**Comment by Vad1mo** [comment]
👏

**Pull request merged**
